<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="MSI" failures="1" tests="1" name="EdgeTest" time="9.917" errors="0" timestamp="2024-06-19T07:10:00 IST">
  <testcase classname="TestClasses.LoginTest" name="Check_Optioncount_and_data" time="0.222">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [5] but found [6]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [5] but found [6]
at TestClasses.LoginTest.Check_Optioncount_and_data(LoginTest.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Check_Optioncount_and_data -->
  <testcase classname="TestClasses.LoginTest" name="Invalid_UsernamePassword" time="0.0">
    <ignored/>
  </testcase> <!-- Invalid_UsernamePassword -->
  <testcase classname="TestClasses.LoginTest" name="SuccessfulLogin" time="0.0">
    <ignored/>
  </testcase> <!-- SuccessfulLogin -->
</testsuite> <!-- EdgeTest -->
