<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="MSI" failures="1" tests="1" name="Test" time="13.473" errors="0" timestamp="2024-07-25T17:25:35 IST">
  <testcase classname="TestClasses.LoginTest" name="Check_Optioncount_and_data" time="1.717">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [5] but found [6]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [5] but found [6]
at TestClasses.LoginTest.Check_Optioncount_and_data(LoginTest.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- Check_Optioncount_and_data -->
  <testcase classname="TestClasses.LoginTest" name="SuccessfulLogin" time="0.0">
    <ignored/>
  </testcase> <!-- SuccessfulLogin -->
  <testcase classname="TestClasses.LoginTest" name="Invalid_UsernamePassword" time="0.0">
    <ignored/>
  </testcase> <!-- Invalid_UsernamePassword -->
</testsuite> <!-- Test -->
